---
- name: Set hostname IP in /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^.*{{ inventory_hostname_short }}"
    line: "{{ ansible_default_ipv4.address }} \
      {{ inventory_hostname }} \
      {{ inventory_hostname_short }}\
      {% for mail_domain in mail_domains %} {{ mail_domain.server_fqdn }}{% endfor %}"

- name: Setup PostgreSQL
  ansible.builtin.import_tasks: setup_postgresql.yml

- name: Setup Dovecot
  ansible.builtin.import_tasks: setup_dovecot.yml

- name: Setup Postfix
  ansible.builtin.import_tasks: setup_postfix.yml

- name: Setup Rspamd
  ansible.builtin.import_tasks: setup_rspamd.yml

- name: Flush hadlers before finish message
  ansible.builtin.meta: flush_handlers

- name: Finish
  ansible.builtin.debug:
    msg:
      - "Job finished!"
      # - ""
      # - "Don't forget to create DNS TXT record {{ dkim_identifier }}._domainkey.{{ mail_domain }}"
      # - "with content from the file {{ dkim_pubkey_file }}"
      # - ""
      # - "Also keep up to date TLS fullchain certificate in {{ cert_fullchain_file }}"
      # - "and TLS key in {{ cert_key_file }}"
      - ""
      - "PostgreSQL user is {{ postgresql.mail_server_user_name }}, password is {{ postgresql.mail_server_user_pass }}"
      - "Database name is {{ postgresql.mail_server_database }}"
      - ""
      - "You need to open ports"
      - "80/tcp, 443/tcp, 443/udp, 25/tcp, 587/tcp, 143/tcp, 993/tcp, 4190/tcp"
      - "in your firewall."
