---
- name: Install Rspamd and dependencies
  ansible.builtin.apt:
    state: present
    name: "{{ item }}"
    update_cache: true
  with_items:
    - rspamd
    - redis-server
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Add _rspamd user to the redis group
  ansible.builtin.user:
    name: _rspamd
    groups: redis
    append: true
