---
- name: Setup nginx
  ansible.builtin.include_role:
    name: setup_nginx_reverse_proxy
  vars:
    template_file_name: cloud.yararchive.ru.conf.j2
    nginx_server_config_file_name: cloud.yararchive.ru.conf
    nginx_server_listen_port: 443
