---
- name: Setup nginx
  ansible.builtin.include_role:
    name: setup_nginx_reverse_proxy
  vars:
    setup_nginx_reverse_proxy_template_file: cloud.yararchive.ru.conf.j2
    setup_nginx_reverse_proxy_config_file: cloud.yararchive.ru.conf
    setup_nginx_reverse_proxy_listen_port: 443
