---
- name: Prepare website directory
  ansible.builtin.file:
    path: "{{ deploy_yararchive_homepage_website_directory }}"
    owner: root
    group: root
    mode: "0755"
    force: false
    state: directory

- name: Unarchive files to website directory
  ansible.builtin.unarchive:
    src: www.tar
    dest: "{{ deploy_yararchive_homepage_website_directory }}"
    owner: root
    group: root
    mode: "0644"

- name: Setup nginx
  ansible.builtin.include_role:
    name: setup_nginx_reverse_proxy
  vars:
    setup_nginx_reverse_proxy_template_file: homepage.yararchive.ru.conf.j2
    setup_nginx_reverse_proxy_config_file: homepage.yararchive.ru.conf
    setup_nginx_reverse_proxy_listen_port: 443
