---
- name: Prepare website directory
  ansible.builtin.file:
    path: "{{ yararchive_homepage_website_directory }}"
    owner: root
    group: root
    mode: 0755
    force: false
    state: directory

- name: Unarchive files to website directory
  ansible.builtin.unarchive:
    src: www.tar
    dest: "{{ yararchive_homepage_website_directory }}"
    owner: root
    group: root
    mode: 0644

- name: Setup nginx
  ansible.builtin.include_role:
    name: setup_nginx_reverse_proxy
  vars:
    template_file_name: homepage.yararchive.ru.conf.j2
    nginx_server_config_file_name: homepage.yararchive.ru.conf
    nginx_server_listen_port: 443
