---
public_ips:
  - 212.232.41.203
mail_domains:
  - name: corp.yararchive.ru
    server_fqdn: m.corp.yararchive.ru
    cert_fullchain_file: "/etc/ssl/certs/*.corp.yararchive.ru_fullchain.cer"
    cert_key_file: "/etc/ssl/private/*.corp.yararchive.ru.key"
  - name: yararchive.ru
    server_fqdn: m.yararchive.ru
    cert_fullchain_file: "/etc/ssl/certs/*.yararchive.ru_fullchain.cer"
    cert_key_file: "/etc/ssl/private/*.yararchive.ru.key"
postgresql:
  host: 127.0.0.1
  port: 5432
  mail_server_database: vmail
  mail_server_user_name: vmail
  mail_server_user_pass: "{{ lookup('ansible.builtin.password', \
    '/dev/null seed=postgresql.mail_server_user_name chars=ascii_letters,digits length=32') }}"
  nextcloud_user_name: nextcloud
  nextcloud_user_pass: "{{ lookup('ansible.builtin.password', \
    '/dev/null seed=postgresql.nextcloud_user_name chars=ascii_letters,digits length=32') }}"
dh_params: /etc/ssl/ffdhe4096.pem
mail_storage_user: vmail
mail_storage_group: vmail
mail_storage_uid: 5000
mail_storage_gid: 5000
mail_storage_user_home: /var/vmail
mailboxes_dir: "{{ [mail_storage_user_home, 'mailboxes'] | ansible.builtin.path_join }}"
sieve_users_dir: "{{ [mail_storage_user_home, 'sieve', '%d', '%n'] | ansible.builtin.path_join }}"
sieve_global_dir: "{{ [mail_storage_user_home, 'sieve', 'global'] | ansible.builtin.path_join }}"
sieve_pipe_bin_dir: /usr/local/bin/dovecot/sieve
