---
- name: Deploy semaphore
  hosts: ansible_semaphore_servers
  gather_facts: true
  become: true

- name: Prepare SSL certificates
  ansible.builtin.import_playbook: deploy_ssl_certificates.yml
