---
- name: Deploy ansible semaphore
  hosts: "{{ ansible_semaphore_hosts_limit | default('ansible_semaphore_servers') }}"
  gather_facts: true
  become: true

  roles:
    - role: deploy_semaphore
