---
mail_domain: yararchive.ru
mail_server_fqdn: "m.{{ mail_domain }}"
webmail_fqdn: "{{ mail_server_fqdn }}"
cert_fullchain_file: /etc/ssl/certs/*.yararchive.ru_fullchain.cer
cert_key_file: /etc/ssl/private/*.yararchive.ru.key
mail_storage_user: vmail
mail_storage_group: vmail
mail_storage_uid: 5000
mail_storage_gid: 5000
mail_storage_user_home: /var/vmail
