---
- name: Create nginx website config
  ansible.builtin.template:
    src: semaphore.conf.j2
    dest: /etc/nginx/sites-available/semaphore.conf
    owner: root
    group: root
    mode: 0644

- name: Create a symbolic link for nginx website config
  ansible.builtin.file:
    src: /etc/nginx/sites-available/semaphore.conf
    dest: /etc/nginx/sites-enabled/semaphore.conf
    owner: root
    group: root
    state: link

- name: Remove nginx default website config
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Start or restart semaphore systemd service
  ansible.builtin.systemd:
    state: restarted
    name: nginx.service
    daemon_reload: true

- name: Wait for webapp start
  ansible.builtin.wait_for:
    port: 443

- name: Allow http and https in ufw
  community.general.ufw:
    rule: allow
    name: "WWW Full"
