---
- name: Install git
  ansible.builtin.apt:
    name: git
    update_cache: true
    state: present

- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    update_cache: true
    state: present
