---
- name: Create systemd service file
  ansible.builtin.template:
    src: semaphore.service.j2
    dest: /etc/systemd/system/semaphore.service
    owner: root
    group: root
    mode: 0644
  register: service_conf

- name: Start or restart semaphore systemd service
  ansible.builtin.systemd:
    state: restarted
    name: semaphore.service
    daemon_reload: true

- name: Wait for webapp start
  ansible.builtin.wait_for:
    port: "{{ semaphore_webapp_port }}"
