---
- name: Prepare dependencies
  ansible.builtin.include_tasks: prepare_dependencies.yml

- name: Prepare perl environment
  ansible.builtin.include_tasks: prepare_perl_environment.yml

- name: Prepare apache
  ansible.builtin.include_tasks: prepare_apache.yml

- name: Setup nginx reverse proxy
  ansible.builtin.include_role:
    name: setup_nginx_reverse_proxy
  vars:
    setup_nginx_reverse_proxy_template_file: yararchive.ru.conf.nginx.j2
    setup_nginx_reverse_proxy_config_file: yararchive.ru.conf
    setup_nginx_reverse_proxy_listen_port: 443
