---
skip_setup_system_email_accounts: false
unattended_updates_notify_email: it@yararchive.ru
apt_daily_timer_directory: /etc/systemd/system/apt-daily.timer.d
apt_daily_upgrade_timer_directory: /etc/systemd/system/apt-daily-upgrade.timer.d
