---
- name: Set DKIM key file permissions
  ansible.builtin.file:
    path: "{{ dkim_key_file }}"
    mode: "0440"
    owner: "{{ rspamd_user }}"
    group: "{{ rspamd_group }}"

- name: Save pubkey file
  ansible.builtin.template:
    src: rspamd/dkim_pubkey.j2
    dest: "{{ dkim_pubkey_file }}"
    owner: "{{ rspamd_user }}"
    group: "{{ rspamd_group }}"
    mode: "0644"

- name: Update DKIM selectors map file
  ansible.builtin.template:
    src: rspamd/dkim_selectors.map.j2
    dest: /etc/rspamd/dkim_selectors.map
    mode: "0644"

- name: Restart rspamd
  ansible.builtin.systemd:
    name: rspamd.service
    state: restarted
