---
- name: Install dependencies
  ansible.builtin.apt:
    name: nfs-common
    update_cache: true
    state: present

- name: Prepare website directory
  ansible.builtin.file:
    path: "{{ deploy_yararchive_mirror_website_directory }}"
    owner: root
    group: root
    mode: "0755"
    force: false
    state: directory

- name: Prepare fstab
  ansible.posix.mount:
    src: "{{ deploy_yararchive_mirror_website_fstab_mount_source }}"
    path: "{{ deploy_yararchive_mirror_website_directory }}"
    opts: "ro,noexec,nosuid,nodev"
    state: mounted
    boot: true
    fstype: nfs

- name: Setup nginx
  ansible.builtin.include_role:
    name: setup_nginx_reverse_proxy
  vars:
    setup_nginx_reverse_proxy_template_file: mirror.yararchive.ru.conf.j2
    setup_nginx_reverse_proxy_config_file: mirror.yararchive.ru.conf
    setup_nginx_reverse_proxy_listen_port: 443
