---
galaxy_info:
  author: zv0r
  description: Deploy ansible semaphore
  license: MIT
  min_ansible_version: "2.7"
  platforms:
    - name: Debian
      versions:
        - all
dependencies:
  - role: debian_based_dist_upgrade
    vars:
      debian_based_dist_upgrade_skip_reboot: true
  - role: deploy_ssl_certificates
    vars:
      ssl_cert_domains:
        - "{{ ssl_cert_domain_name }}"
      deploy_ssl_certificates_hosts: "{{ ansible_semaphore_hosts_limit | default('ansible_semaphore_servers') }}"
