---
galaxy_info:
  author: zv0r
  description: Setup Samba AD DC
  license: MIT
  min_ansible_version: "2.7"
  platforms:
    - name: Debian
      versions:
        - all
dependencies:
  - role: setup_bind_dns_server
  - role: setup_chrony
