---
- name: Setup nginx
  ansible.builtin.include_role:
    name: setup_nginx_reverse_proxy
  vars:
    template_file_name: af5.yararchive.ru.conf.j2
    nginx_server_config_file_name: "{{ af5_server_name }}.conf"
    nginx_server_listen_port: 443
