---
galaxy_info:
  author: zv0r
  description: Deploy mail server
  license: MIT
  min_ansible_version: "2.7"
  platforms:
    - name: Debian
      versions:
        - all
dependencies:
  - role: debian_based_dist_upgrade
  - role: deploy_https_certificates
