---
- name: Install packages
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: true
    state: present
  with_items:
    - samba
    - krb5-config
    - winbind
    - smbclient
    - krb5-user
    - rsync

- name: Disable samba file server systemd services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    masked: true
    enabled: false
  with_items:
    - smbd.service
    - nmbd.service
    - winbind.service

- name: Unmask but disable Samba AD DC systemd service
  ansible.builtin.systemd:
    name: samba-ad-dc.service
    state: stopped
    masked: false
    enabled: false

- name: Put ufw app config in the applications.d directory
  ansible.builtin.template:
    src: yararchive-samba-ad-dc.j2
    dest: "/etc/ufw/applications.d/yararchive-samba-ad-dc"
    owner: root
    group: root
    mode: "0644"

- name: Prepare krb5.conf
  ansible.builtin.template:
    src: krb5.conf.j2
    dest: "/etc/krb5.conf"
    owner: root
    group: root
    mode: "0644"

- name: Prepare sysvol-replication.service
  ansible.builtin.template:
    src: sysvol-replication.service.j2
    dest: "/etc/systemd/system/sysvol-replication.service"
    owner: root
    group: root
    mode: "0644"

- name: Prepare sysvol-replication.timer
  ansible.builtin.template:
    src: sysvol-replication.timer.j2
    dest: "/etc/systemd/system/sysvol-replication.timer"
    owner: root
    group: root
    mode: "0644"

- name: Enable SysVol replication systemd service and timer
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    masked: false
    enabled: true
  with_items:
    - sysvol-replication.service
    - sysvol-replication.timer

- name: Open ports with ufw
  community.general.ufw:
    rule: allow
    name: "Samba AD DC"

- name: Replace localhost IP to actual IP at /etc/hosts file
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^127.*{{ inventory_hostname }}"
    line: "{{ ansible_host }} {{ inventory_hostname }} {{ inventory_hostname_short }}"
    owner: root
    group: root
    mode: "0644"
