---
- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    update_cache: true
    state: present

- name: Remove nginx default website config
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Open ports with ufw
  community.general.ufw:
    rule: allow
    name: WWW Full

- name: Setup nginx reverse proxy
  ansible.builtin.include_tasks: prepare_nginx_server_config.yml

- name: Start or restart semaphore systemd service
  ansible.builtin.systemd:
    state: restarted
    name: nginx.service
    daemon_reload: true
