---
- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    update_cache: true
    state: present

- name: Remove nginx default website config
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Start or restart semaphore systemd service
  ansible.builtin.systemd:
    state: restarted
    name: nginx.service
    daemon_reload: true
