---
- name: Install nginx
  ansible.builtin.apt:
    name: nginx
    update_cache: true
    state: present

- name: Remove nginx default website config
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Setup nginx reverse proxy
  ansible.builtin.include_tasks: prepare_nginx_server_config.yml
