---
- name: Prepare nginx server config
  when: template_file_name is defined and nginx_server_config_file_name is defined and nginx_server_listen_port is defined
  block:
    - name: Create nginx website config
      ansible.builtin.template:
        src: "{{ template_file_name }}"
        dest: "/etc/nginx/sites-available/{{ nginx_server_config_file_name }}"
        owner: root
        group: root
        mode: 0644

    - name: Create a symbolic link for nginx website config
      ansible.builtin.file:
        src: "/etc/nginx/sites-available/{{ nginx_server_config_file_name }}"
        dest: "/etc/nginx/sites-enabled/{{ nginx_server_config_file_name }}"
        owner: root
        group: root
        state: link

    - name: Start or restart nginx systemd service
      ansible.builtin.systemd:
        state: restarted
        name: nginx.service
        daemon_reload: true

    - name: Wait for webapp start
      ansible.builtin.wait_for:
        port: "{{ nginx_server_listen_port }}"
