---
- name: Prepare nginx server config
  block:
    - name: Create nginx website config
      ansible.builtin.template:
        src: "{{ template_file_name }}"
        dest: "/etc/nginx/sites-available/{{ nginx_server_config_file_name }}"
        owner: root
        group: root
        mode: "0644"

    - name: Create a symbolic link for nginx website config
      ansible.builtin.file:
        src: "/etc/nginx/sites-available/{{ nginx_server_config_file_name }}"
        dest: "/etc/nginx/sites-enabled/{{ nginx_server_config_file_name }}"
        owner: root
        group: root
        state: link

    - name: Start or restart nginx systemd service
      ansible.builtin.systemd:
        state: restarted
        name: nginx.service
