---
- name: Prepare nginx server config
  block:
    - name: Create nginx website config
      ansible.builtin.template:
        src: "{{ setup_nginx_reverse_proxy_template_file }}"
        dest: "/etc/nginx/sites-available/{{ setup_nginx_reverse_proxy_config_file }}"
        owner: root
        group: root
        mode: "0644"

    - name: Create a symbolic link for nginx website config
      ansible.builtin.file:
        src: "/etc/nginx/sites-available/{{ setup_nginx_reverse_proxy_config_file }}"
        dest: "/etc/nginx/sites-enabled/{{ setup_nginx_reverse_proxy_config_file }}"
        owner: root
        group: root
        state: link

    - name: Start or restart nginx systemd service
      ansible.builtin.systemd:
        state: restarted
        name: nginx.service
