---
galaxy_info:
  author: zv0r
  description: Setup unattended upgrades
  license: MIT
  min_ansible_version: "2.8"
  platforms:
    - name: Debian
      versions:
        - all
dependencies:
  - role: debian_based_dist_upgrade
  - role: setup_system_email_accounts
    when: not skip_setup_system_email_accounts
