---
- name: Update packages list on debian based distro
  ansible.builtin.include_tasks: apt_update.yml

- name: Upgrade debian based distro
  ansible.builtin.include_tasks: dist_upgrade.yml

- name: Reboot after upgrade if needed
  ansible.builtin.include_tasks: reboot_after_upgrade.yml
