---
- name: Check if a reboot is needed on all servers
  register: reboot_required_file
  ansible.builtin.stat:
    path: /var/run/reboot-required
    get_md5: false

- name: Reboot the box if kernel updated
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible for kernel updates"
    connect_timeout: 60
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 90
    test_command: uptime
  when: reboot_required_file.stat.exists and not debian_based_dist_upgrade_skip_reboot
