---
- name: Install Postfix and dependencies
  ansible.builtin.apt:
    state: present
    name: "{{ item }}"
    update_cache: true
  with_items:
    - postfix
    - postfix-pgsql
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Copy Postfix configs
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: postfix/pgsql-virtual-mailbox-domains.cf.j2, dest: /etc/postfix/pgsql-virtual-mailbox-domains.cf, mode: "0640", group: postfix }
    - { src: postfix/pgsql-virtual-mailbox-maps.cf.j2, dest: /etc/postfix/pgsql-virtual-mailbox-maps.cf, mode: "0640", group: postfix }
    - { src: postfix/pgsql-virtual-alias-maps.cf.j2, dest: /etc/postfix/pgsql-virtual-alias-maps.cf, mode: "0640", group: postfix }
    - { src: postfix/main.cf.j2, dest: /etc/postfix/main.cf, mode: "0644", group: root }
    - { src: postfix/master.cf.j2, dest: /etc/postfix/master.cf, mode: "0644", group: root }
  notify: Restart Postfix
