---
- name: "Create directories for {{ mail_domain.name }}"
  ansible.builtin.file:
    state: directory
    path: "/var/www/autoconfig.{{ mail_domain.name }}/mail"
    mode: "0775"
    owner: www-data
    group: www-data

- name: "Put xml config in /var/www/autoconfig.{{ mail_domain.name }}"
  ansible.builtin.template:
    src: autoconfig/config-v1.1.xml.j2
    dest: "/var/www/autoconfig.{{ mail_domain.name }}/mail/config-v1.1.xml"
    mode: "0644"
    owner: www-data
    group: www-data

- name: "Create Apache virtual host config for autoconfig.{{ mail_domain.name }}"
  ansible.builtin.template:
    src: autoconfig/autoconfig.apache.j2
    dest: "/etc/apache2/sites-available/autoconfig.{{ mail_domain.name }}.conf"
    mode: "0644"

- name: "Enable site autoconfig.{{ mail_domain.name }}"
  ansible.builtin.command: "a2ensite autoconfig.{{ mail_domain.name }}"
  failed_when: false
  changed_when: true
