---
- name: Set hostname IP in /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^.*{{ inventory_hostname_short }}"
    line: "{{ ansible_default_ipv4.address }} {{ inventory_hostname }} {{ inventory_hostname_short }} {{ mail_server_fqdn }}"

- name: Setup PostgreSQL
  ansible.builtin.import_tasks: setup_postgresql.yml

- name: Setup Postfix
  ansible.builtin.import_tasks: setup_postfix.yml

- name: Flush hadlers before finish message
  ansible.builtin.meta: flush_handlers

- name: Finish
  ansible.builtin.debug:
    msg:
      - "Job finished!"
      - ""
      - "Don't forget to create DNS TXT record {{ dkim_identifier }}._domainkey.{{ mail_domain }}"
      - "with content from the file {{ dkim_pubkey_file }}."
      - ""
      - "Also keep up to date TLS fullchain certificate in {{ cert_fullchain_file }}"
      - "and TLS key in {{ cert_key_file }}."
      - ""
      - "You need to open http and https ports in your firewall."
