---
- name: Set hostname IP in /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^.*{{ inventory_hostname_short }}"
    line: "{{ ansible_default_ipv4.address }} \
      {{ inventory_hostname }} \
      {{ inventory_hostname_short }}\
      {{ roundcube.server_fqdn }} \
      {% for mail_domain in mail_domains %} \
      {{ mail_domain.server_fqdn }}\
      {% if mail_domain.aliases is defined %}\
      {% for alias in mail_domain.aliases %} \
      {{ alias.name }}
      {% endfor %}
      {% endif %}
      {% endfor %}"

- name: Setup PostgreSQL
  ansible.builtin.import_tasks: setup_postgresql.yml

- name: Setup Postfix
  ansible.builtin.import_tasks: setup_postfix.yml

- name: Setup Dovecot
  ansible.builtin.import_tasks: setup_dovecot.yml

- name: Setup Rspamd
  ansible.builtin.import_tasks: setup_rspamd.yml

- name: Setup mail clients autoconfig
  ansible.builtin.import_tasks: setup_mail_clients_autoconfig.yml

- name: Setup Roundcube
  ansible.builtin.import_tasks: setup_roundcube.yml

- name: Flush hadlers before finish message
  ansible.builtin.meta: flush_handlers

- name: Finish
  ansible.builtin.debug:
    msg:
      - "Job finished!"
      - ""
      - "Don't forget to create DNS TXT record {{ rspamd.dkim_id }}._domainkey for domains"
      - "{% for mail_domain in mail_domains %}{{ mail_domain.name }} {% endfor %}"
      - "check directory {{ rspamd.dkim_dir }}"
      - ""
      - "Also keep up to date TLS fullchain certificates and TLS keys"
      - ""
      - "You can adjust php.ini params like date.timezone, upload_max_filesize, post_max_size"
      - "for better logging and big messages attachments."
      - ""
      - "It is recommecded to create TXT records for your domains:"
      - "@ IN TXT \"v=spf1 mx -all\""
      - "_dmarc IN TXT \"v=DMARC1; p=reject; rua=mailto:it@{{ mail_domains[0].name }}; adkim=s; aspf=s; pct=100;\""
      - ""
      - "PostgreSQL user is {{ postgresql.mail_server_user_name }}, password is {{ postgresql.mail_server_user_pass }}"
      - "Database name is {{ postgresql.mail_server_database }}"
      - ""
      - "You need to open these ports in your firewall:"
      - "80/tcp, 443/tcp, 25/tcp, 587/tcp, 143/tcp, 993/tcp, 4190/tcp"
