---
- name: Install apache2
  ansible.builtin.apt:
    name: apache2
    update_cache: true
    state: present

- name: Setup local vhosts configs
  ansible.builtin.include_tasks: local_vhosts_configs.yml
  vars:
    template_local_config: true
  loop: "{{ deploy_mail_server_mail_domains }}"
  loop_control:
    loop_var: mail_domain
