---
- name: Install Rspamd and dependencies
  ansible.builtin.apt:
    state: present
    name: rspamd
    update_cache: true
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Copy rspamd configs
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - { src: rspamd/milter_headers.conf.j2, dest: /etc/rspamd/override.d/milter_headers.conf }
    - { src: rspamd/dkim_signing.conf.j2, dest: /etc/rspamd/local.d/dkim_signing.conf }
    - { src: rspamd/dkim_selectors.map.j2, dest: /etc/rspamd/dkim_selectors.map }
  notify: Restart Rspamd

- name: Create rspamd dkim directory
  ansible.builtin.file:
    state: directory
    path: "{{ dkim_directory }}"
    owner: "{{ rspamd_user }}"
    group: "{{ rspamd_group }}"
    mode: "0770"

- name: Generate DKIM
  ansible.builtin.command: "rspamadm dkim_keygen \
    -d {{ mail_domain }} \
    -s {{ dkim_identifier }} \
    -k {{ dkim_key_file | ansible.builtin.quote }}"
  changed_when: true
  failed_when: false
  register: dkim_pubkey
  when: skip_dkim_gen is not defined

- name: Set DKIM key file permissions
  ansible.builtin.file:
    path: "{{ dkim_key_file }}"
    mode: "0440"
    owner: "{{ rspamd_user }}"
    group: "{{ rspamd_group }}"

- name: Save pubkey file
  ansible.builtin.template:
    src: rspamd/dkim_pubkey.j2
    dest: "{{ dkim_pubkey_file }}"
    owner: "{{ rspamd_user }}"
    group: "{{ rspamd_group }}"
    mode: "0644"
  notify: Restart Rspamd
